[project]
name = "motionlab"
version = "0.1.0"
description = "Analysing structural positional bias in competitive debating motions"
requires-python = ">=3.12"
dependencies = [
    "httpx>= 0.27"
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]